In [1]:
import pandas as pd
import numpy as np
import warnings
import tqdm

from PIL import Image

import swanlab
import json

In [7]:
df = pd.read_pickle(r"D:\workspace\AO-shaping\data\wf-less\20251112_194423\a4506915-596f-4c55-92cd-53dd3af1e868.pkl", compression='zip')

with open(r"D:\workspace\AO-shaping\data\wf-less\20251112_194423\a4506915-596f-4c55-92cd-53dd3af1e868.json") as f:
    config = json.load(f)
    config['dump_path'] = r"D:\workspace\AO-shaping\data\wf-less\20251112_194423"
    config['experiment_date'] = "20251112"

df.head(2)

,J,pib,p%,max_r,_v,_img,_diff,lr,r,delta,_epoch
0,8925.0,1.0,0.500308,42.784424,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",0.0,2.0,42.784424,2,0
1,7862.5,0.0,0.503602,42.784424,"[0.0, 0.0001999999999876323, -0.00019999999998...","[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",-81.0,2.0,42.784424,2,1

In [8]:
def img_to_swan_img(img):
    return swanlab.Image(img)

def v_to_swan_bar(v):
    bar  = swanlab.echarts.Bar()
    bar.add_xaxis(list(range(len(v))))
    bar.add_yaxis("v", v.tolist())
    return bar


df['v'] = df['_v'].apply(v_to_swan_bar)
df['img'] = df['_img'].apply(img_to_swan_img)
df['diff'] = df['_diff']

df.head(2)

,J,pib,p%,max_r,_v,_img,_diff,lr,r,delta,_epoch,v,img,diff
0,8925.0,1.0,0.500308,42.784424,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",0.0,2.0,42.784424,2,0,<pyecharts.charts.basic_charts.bar.Bar object ...,<swanlab.data.modules.image.Image object at 0x...,0.0
1,7862.5,0.0,0.503602,42.784424,"[0.0, 0.0001999999999876323, -0.00019999999998...","[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",-81.0,2.0,42.784424,2,1,<pyecharts.charts.basic_charts.bar.Bar object ...,<swanlab.data.modules.image.Image object at 0x...,-81.0

In [ ]:
swanlab.init(
    project="AO-shaping",
    experiment_name="a4506915-596f-4c55-92cd-53dd3af1e868",
    config=config,
    description="Axis Spot PIB Test"
)

Output()

Output()

swanlab: Tracking run with swanlab version 0.7.1

swanlab: Run data will be saved locally in
d:\workspace\AO-shaping\notebooks\swanlog\run-20251115_162933-39g5owcibflqjbn78nexg

swanlab: 👋 Hi zhanghao,welcome to swanlab!

swanlab: Syncing run a4506915-596f-4c55-92cd-53dd3af1e868 to the cloud

swanlab: 🏠 View project at https://swanlab.cn/@zhanghao/notebooks

swanlab: 🚀 View run at https://swanlab.cn/@zhanghao/notebooks/runs/39g5owcibflqjbn78nexg

In [10]:
for i, row in tqdm.tqdm(df.iterrows()):
    row['v'] = v_to_swan_bar(row['_v'])
    log = {k:v for k,v in row.to_dict().items() if not k.startswith('_')}
    swanlab.log(log)

10001it [00:32, 306.01it/s]

In [11]:
swanlab.finish()

swanlab: 🏠 View project at https://swanlab.cn/@zhanghao/notebooks

swanlab: 🚀 View run at https://swanlab.cn/@zhanghao/notebooks/runs/39g5owcibflqjbn78nexg